### ISSUE TITLE
Define package.json file with dependencies

### ISSUE THREAD

**Issue by juanmirocks** [raharjaliu/pubseq_webinterface#1]
See:

```
node app.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jmcejuela/git/pubseq_webinterface/pubseq_webapp/app.js:1:77)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by raharjaliu** [comment]
@jmcejuela 

You have to install dependencies before running Node.js. See (http://stackoverflow.com/questions/8367031/how-do-i-install-package-json-dependencies-in-the-current-directory-using-npm).

I have updated the running manual to include that (https://github.com/raharjaliu/pubseq_webinterface/blob/master/pubseq_webapp/README.md).

Also note that you should comment lines 38-39 of file `views/search.jade`and move the line `window.location.replace('/results');` (line 54) to right after `console.log("GET-ing from Solr server");` (line 36). That part communicates with Solr server and since you don't have Solr server, it will throw an exception.

**Comment by juanmirocks** [comment]
OK, but now you've defined the package.json file. That's the important bit.

Also please put the info of the commenting out stuff on the README. All
info must be contained in the repo, not in emails. Emails get lost.

**Comment by raharjaliu** [comment]
updated (https://github.com/raharjaliu/pubseq_webinterface/blob/master/pubseq_webapp/README.md). Note that in my previous coment I said "comment line 38-39". It should be "38-60".
